### ISSUE TITLE
Cant use Resetbal

### ISSUE THREAD

**Issue by Op0m** [Average-Org/SimpleEcon#1]
So i find some Glitch where i cant use These command.everytime i use it is  said "Command Failed" and after got that error i check the log and find this:

2022-12-19 03:44:14 - Utils: INFO: Redigit executed: /resetbal 10.
2022-12-19 03:44:14 - Command: ERROR: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at SimpleEcon.SimpleEcon.ResetBal(CommandArgs args)
   at TShockAPI.Command.Run(String msg, Boolean silent, TSPlayer ply, List`1 parms)

**Comment by Op0m** [comment]
Oh yeah i forget if i want to reset my alt balance to 0

**Comment by RenderBr** [comment]
> Oh yeah i forget if i want to reset my alt balance to 0

Consider using this **much** better plugin: https://github.com/Terraria-Builders-Community/Banker

It is a full rewrite by me, however the only downside is you need a mongodb setup to use it since it depends on Auxiliary (by TBC). It also depends on CSF.Net.TShock. However, it is worth it if you want a better economy plugin and also more frequent updates.

As for this plugin, I will get around to fixing this issue.

**Comment by RenderBr** [comment]
> Oh yeah i forget if i want to reset my alt balance to 0

Oh, just realized what's wrong here. You don't /resetbal 10. ???? /setbal 10 is how you set a specific currency. /resetbal <player> is how you reset a player's balance to 0.

That is why it is throwing an error. LOL

**Comment by Op0m** [comment]
> > Oh yeah i forget if i want to reset my alt balance to 0
> 
> Oh, just realized what's wrong here. You don't /resetbal 10. ???? /setbal 10 is how you set a specific currency. /resetbal is how you reset a player's balance to 0.
> 
> That is why it is throwing an error. LOL

I mean i reset my alt account that name its 10

**Comment by Op0m** [comment]
Ok

> > Oh yeah i forget if i want to reset my alt balance to 0
> 
> Consider using this **much** better plugin: https://github.com/Terraria-Builders-Community/Banker
> 
> It is a full rewrite by me, however the only downside is you need a mongodb setup to use it since it depends on Auxiliary (by TBC). It also depends on CSF.Net.TShock. However, it is worth it if you want a better economy plugin and also more frequent updates.
> 
> As for this plugin, I will get around to fixing this issue.

But ok then i will try using mongodb even i dont know how to use database

**Comment by Op0m** [comment]
Oh another thing i try reset my Account too so yeah i will trying using Db

**Comment by Op0m** [comment]
> > Oh yeah i forget if i want to reset my alt balance to 0
> 
> Consider using this **much** better plugin: https://github.com/Terraria-Builders-Community/Banker
> 
> It is a full rewrite by me, however the only downside is you need a mongodb setup to use it since it depends on Auxiliary (by TBC). It also depends on CSF.Net.TShock. However, it is worth it if you want a better economy plugin and also more frequent updates.
> 
> As for this plugin, I will get around to fixing this issue.

Ok but how connect Database to server? i dont know how to use database (still newbie on Database)

**Comment by Op0m** [comment]
> > Oh yeah i forget if i want to reset my alt balance to 0
> 
> Oh, just realized what's wrong here. You don't /resetbal 10. ???? /setbal 10 is how you set a specific currency. /resetbal is how you reset a player's balance to 0.
> 
> That is why it is throwing an error. LOL

Oh i think i know why (just my theory): the Code think 0 its negative number but actually 0 is a positive number

**Comment by RenderBr** [comment]
> > > Oh yeah i forget if i want to reset my alt balance to 0
> 
> > 
> 
> > Oh, just realized what's wrong here. You don't /resetbal 10. ???? /setbal 10 is how you set a specific currency. /resetbal is how you reset a player's balance to 0.
> 
> > 
> 
> > That is why it is throwing an error. LOL
> 
> 
> 
> Oh i think i know why (just my theory): the Code think 0 its negative number but actually 0 is a positive number

no? if your inputting 10 that is completely false

**Comment by RenderBr** [comment]
> > > Oh yeah i forget if i want to reset my alt balance to 0
> 
> > 
> 
> > Oh, just realized what's wrong here. You don't /resetbal 10. ???? /setbal 10 is how you set a specific currency. /resetbal is how you reset a player's balance to 0.
> 
> > 
> 
> > That is why it is throwing an error. LOL
> 
> 
> 
> Oh i think i know why (just my theory): the Code think 0 its negative number but actually 0 is a positive number

no? if your inputting 10 that is completely false
